using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class movement : MonoBehaviour
{
    Rigidbody rb;
    float speed = 3.0f;

    void Start()
    {
        rb = GetComponent<Rigidbody> ();
    }

    void Update()
    {
        if(Input.GetKey(KeyCode.UpArrow)){
            rb.velocity = transform.forward*speed;
        }
        if(Input.GetKey(KeyCode.DownArrow)){
            rb.velocity = -transform.forward*speed;
        }
        if(Input.GetKey(KeyCode.RightArrow)){
            rb.velocity = transform.right*speed;
        }
        if(Input.GetKey(KeyCode.LeftArrow)){
            rb.velocity = -transform.right*speed;
        }
    }
}